### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by lugosieben**
This adds the german translation for every currently available translation key.

Btw: if there are formatting mistakes, i will correct them tomorrow when I‘m back home & at my PC. Github mobile shows me 2 completely different looks depending if I‘m in the web app or the application.

### CODE REVIEW

**Comment by lugosieben** [comment]
Oh, and my frii.site user is Lugo

**Review by ctih1 — APPROVED** [review]
Great work, thank you for the translations!

**Comment by ctih1** [comment]
Since german is spoken by 90 million people, I'll give you be getting 2 extra domains, as said here: https://github.com/ctih1/frii.site-frontend/wiki/Translation-guide

**Comment by ctih1** [comment]
Added! You should see `max-domains` set to 6 when you download your GDPR data from https://frii.site/account/manage
Thank you for the translation! 🙂

**Comment by lugosieben** [comment]
> Added! You should see `max-domains` (inside `permissions`) set to 6 when you download your GDPR data from https://frii.site/account/manage Thank you for the translation! 🙂

No, im not seeing anything, weird. My `permissions` is just an empty array. Maybe it's because the username that I log in with is Lugo but in https://www.frii.site/account/manage it says that my username is this 64 char string?

**Comment by ctih1** [comment]
That is indeed strange, your username in https://frii.site/account/manage is the sha256 hash of your actual username, (6ec4365f03f10e708241762dac5813c11a7e26e679c103b2b1fdd213cd793b9c right?), I'll quickly check the database for the change 🙂

**Comment by ctih1** [comment]
It seems like the data wasn't properly saved to the database, you should have the correct permissions now

**Comment by lugosieben** [comment]
Yep, that worked 😄 ty

**Pull request merged**
