### PR TITLE
Change “Report Abuse or Vulnerability” to “Report” in German translation

### PR DESCRIPTION
**Pull request by lugosieben**
Sorry for the late response, im on vacation right now so I unfortunately didn’t see it

### CODE REVIEW

**Comment by lugosieben** [comment]
Oh wait, sorry that this merges into the master branch, I only saw that now…

**Comment by ctih1** [comment]
No need to apologize for being on vacation! Thank you for the contribution and enjoy your vacation 🙂

**Review by ctih1 — APPROVED** [review]
Excellent

**Comment by ctih1** [comment]
#97

**Pull request merged**
